### ISSUE TITLE
The type or namespace name 'CropImageView' could not be found

### ISSUE THREAD

**Issue by draugaslt** [mikescandy/Xamarin-Cropper#3] opened 2017-06-14 09:04 UTC
Error CS0246: The type or namespace name 'CropImageView' could not be found (are you missing a using directive or an assembly reference?) (CS0246) (SampleApp)

What did i missed?

**Comment by mikescandy** [comment] 2017-06-14 19:29
not sure, haven't check this project in a while (although the library is working fine in a different project). will review and post back!

**Comment by mikescandy** [comment] 2017-06-14 21:09
Hi, i just checked out the project and it runs fine on my machine. Would you be able to post the build output?

**Comment by mikescandy** [comment] 2017-11-23 19:14
can't reproduce, closing.

**Closed as completed by mikescandy** 2017-11-23 19:14 UTC
